

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "p_0009_WEBFE_T003_Contacts\Web.config"
//     Connection String Name: "connT003"
//     Connection String:      "Server=WBSQL1\PROD;Database=d3_JPHSA_All_Users;Persist Security Info=True;User ID=d3_WebFE;password=**zapped**;;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition: Core-based Licensing (64-bit)
// Database Engine Edition: Enterprise

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace p_0009_WEBFE_T003_Contacts
{
    using System.Linq;

    #region Unit of work

    public interface IcontactDBContext : System.IDisposable
    {
        System.Data.Entity.DbSet<T000MvcLogging> T000MvcLogging { get; set; } // T000_MVC_Logging
        System.Data.Entity.DbSet<T003TelephoneContact> T003TelephoneContact { get; set; } // T003_Telephone_Contacts

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel> Prj0018Rep001SearchTelephoneContacts(string searchString);
        System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel> Prj0018Rep001SearchTelephoneContacts(string searchString, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel>> Prj0018Rep001SearchTelephoneContactsAsync(string searchString);

    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class contactDBContext : System.Data.Entity.DbContext, IcontactDBContext
    {
        public System.Data.Entity.DbSet<T000MvcLogging> T000MvcLogging { get; set; } // T000_MVC_Logging
        public System.Data.Entity.DbSet<T003TelephoneContact> T003TelephoneContact { get; set; } // T003_Telephone_Contacts

        static contactDBContext()
        {
            System.Data.Entity.Database.SetInitializer<contactDBContext>(null);
        }

        public contactDBContext()
            : base("Name=connT003")
        {
        }

        public contactDBContext(string connectionString)
            : base(connectionString)
        {
        }

        public contactDBContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public contactDBContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public contactDBContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new T000MvcLoggingConfiguration());
            modelBuilder.Configurations.Add(new T003TelephoneContactConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new T000MvcLoggingConfiguration(schema));
            modelBuilder.Configurations.Add(new T003TelephoneContactConfiguration(schema));
            return modelBuilder;
        }

        // Stored Procedures
        public System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel> Prj0018Rep001SearchTelephoneContacts(string searchString)
        {
            int procResult;
            return Prj0018Rep001SearchTelephoneContacts(searchString, out procResult);
        }

        public System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel> Prj0018Rep001SearchTelephoneContacts(string searchString, out int procResult)
        {
            var searchStringParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@SearchString", SqlDbType = System.Data.SqlDbType.NVarChar, Direction = System.Data.ParameterDirection.Input, Value = searchString, Size = 100 };
            if (searchStringParam.Value == null)
                searchStringParam.Value = System.DBNull.Value;

            var procResultParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@procResult", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output };
            var procResultData = Database.SqlQuery<Prj0018Rep001SearchTelephoneContactsReturnModel>("EXEC @procResult = [dbo].[prj_0018_REP_001_Search_TelephoneContacts] @SearchString", searchStringParam, procResultParam).ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async System.Threading.Tasks.Task<System.Collections.Generic.List<Prj0018Rep001SearchTelephoneContactsReturnModel>> Prj0018Rep001SearchTelephoneContactsAsync(string searchString)
        {
            var searchStringParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@SearchString", SqlDbType = System.Data.SqlDbType.NVarChar, Direction = System.Data.ParameterDirection.Input, Value = searchString, Size = 100 };
            if (searchStringParam.Value == null)
                searchStringParam.Value = System.DBNull.Value;

            var procResultData = await Database.SqlQuery<Prj0018Rep001SearchTelephoneContactsReturnModel>("EXEC [dbo].[prj_0018_REP_001_Search_TelephoneContacts] @SearchString", searchStringParam).ToListAsync();

            return procResultData;
        }

    }
    #endregion

    #region POCO classes

    // T000_MVC_Logging
    [Table("T000_MVC_Logging", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class T000MvcLogging
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"T000_PK", Order = 1, TypeName = "int")]
        [Index(@"T000$T000_PK", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "T 000 pk")]
        public int T000Pk { get; set; } // T000_PK (Primary key)

        [Column(@"ApplicationAssemblyName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Application assembly name")]
        public string ApplicationAssemblyName { get; set; } // ApplicationAssemblyName (length: 255)

        [Column(@"Browser", Order = 3, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Browser")]
        public string Browser { get; set; } // Browser (length: 100)

        [Column(@"Create_Update_Delete_Read", Order = 4, TypeName = "nvarchar")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Create update delete read")]
        public string CreateUpdateDeleteRead { get; set; } // Create_Update_Delete_Read (length: 6)

        [Column(@"DateTimeCreated", Order = 5, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date time created")]
        public System.DateTime DateTimeCreated { get; set; } // DateTimeCreated

        [Column(@"Note", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"UserLogIn", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "User log in")]
        public string UserLogIn { get; set; } // UserLogIn

        [Column(@"IP", Order = 8, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Ip")]
        public string Ip { get; set; } // IP (length: 15)

        [Column(@"ComputerName", Order = 9, TypeName = "nvarchar(max)")]
        [Display(Name = "Computer name")]
        public string ComputerName { get; set; } // ComputerName

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column(@"T000_RowVersion", Order = 10, TypeName = "timestamp")]
        [Display(Name = "T 000 row version")]
        public byte[] T000RowVersion { get; private set; } // T000_RowVersion

        public T000MvcLogging()
        {
            DateTimeCreated = System.DateTime.Now;
        }
    }

    // T003_Telephone_Contacts
    [Table("T003_Telephone_Contacts", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class T003TelephoneContact
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"T003_PK", Order = 1, TypeName = "int")]
        [Index(@"T003$T003_PK", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "T 003 pk")]
        public int T003Pk { get; set; } // T003_PK (Primary key)

        [Column(@"Toshiba_DisplayName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Toshiba display name")]
        public string ToshibaDisplayName { get; set; } // Toshiba_DisplayName (length: 255)

        [Column(@"Display_For_Users", Order = 3, TypeName = "nvarchar")]
        [MaxLength(55)]
        [StringLength(55)]
        [Display(Name = "Display for users")]
        public string DisplayForUsers { get; set; } // Display_For_Users (length: 55)

        [Column(@"ShowUsers_0_1", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Show users 0 1")]
        public bool ShowUsers01 { get; set; } // ShowUsers_0_1

        [Column(@"Ext_OLD", Order = 5, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Ext old")]
        public string ExtOld { get; set; } // Ext_OLD (length: 10)

        [Column(@"Ext_Toshiba", Order = 6, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Ext toshiba")]
        public string ExtToshiba { get; set; } // Ext_Toshiba (length: 255)

        [Column(@"Position", Order = 7, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Position")]
        public string Position { get; set; } // Position (length: 255)

        [Column(@"Department", Order = 8, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Department")]
        public string Department { get; set; } // Department (length: 255)

        [Column(@"Fax", Order = 9, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Fax")]
        public string Fax { get; set; } // Fax (length: 100)

        [Column(@"Email", Order = 10, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 255)

        [Column(@"PhoneNumber", Order = 11, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } // PhoneNumber (length: 100)

        [Column(@"Last_Name", Order = 12, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // Last_Name (length: 255)

        [Column(@"First_Name", Order = 13, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // First_Name (length: 255)

        [Column(@"EB_WB", Order = 14, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Eb wb")]
        public string EbWb { get; set; } // EB_WB (length: 15)

        [Column(@"Toshiba_Directory_Type", Order = 15, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Toshiba directory type")]
        public string ToshibaDirectoryType { get; set; } // Toshiba_Directory_Type (length: 100)

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column(@"T003_RowVersion", Order = 16, TypeName = "timestamp")]
        [Display(Name = "T 003 row version")]
        public byte[] T003RowVersion { get; private set; } // T003_RowVersion

        [Column(@"IT_Notes", Order = 17, TypeName = "nvarchar(max)")]
        [Display(Name = "It notes")]
        public string ItNotes { get; set; } // IT_Notes

        public T003TelephoneContact()
        {
            ShowUsers01 = true;
        }
    }

    #endregion

    #region POCO Configuration

    // T000_MVC_Logging
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class T000MvcLoggingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<T000MvcLogging>
    {
        public T000MvcLoggingConfiguration()
            : this("dbo")
        {
        }

        public T000MvcLoggingConfiguration(string schema)
        {
            Property(x => x.ApplicationAssemblyName).IsOptional();
            Property(x => x.Browser).IsOptional();
            Property(x => x.CreateUpdateDeleteRead).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.UserLogIn).IsOptional();
            Property(x => x.Ip).IsOptional();
            Property(x => x.ComputerName).IsOptional();
            Property(x => x.T000RowVersion).IsOptional();
        }
    }

    // T003_Telephone_Contacts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class T003TelephoneContactConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<T003TelephoneContact>
    {
        public T003TelephoneContactConfiguration()
            : this("dbo")
        {
        }

        public T003TelephoneContactConfiguration(string schema)
        {
            Property(x => x.ToshibaDisplayName).IsOptional();
            Property(x => x.DisplayForUsers).IsOptional();
            Property(x => x.ExtOld).IsOptional();
            Property(x => x.ExtToshiba).IsOptional();
            Property(x => x.Position).IsOptional();
            Property(x => x.Department).IsOptional();
            Property(x => x.Fax).IsOptional();
            Property(x => x.Email).IsOptional();
            Property(x => x.PhoneNumber).IsOptional();
            Property(x => x.LastName).IsOptional();
            Property(x => x.FirstName).IsOptional();
            Property(x => x.EbWb).IsOptional();
            Property(x => x.ToshibaDirectoryType).IsOptional();
            Property(x => x.T003RowVersion).IsOptional();
            Property(x => x.ItNotes).IsOptional();
        }
    }

    #endregion

    #region Stored procedure return models

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class Prj0018Rep001SearchTelephoneContactsReturnModel
    {
        public System.Int32 T003_PK { get; set; }
        public System.String Name { get; set; }
        public System.String Ext { get; set; }
        public System.String Position { get; set; }
        public System.String Department { get; set; }
        public System.String Fax { get; set; }
        public System.String Email { get; set; }
        public System.String PhoneNumber { get; set; }
        public System.String Last_Name { get; set; }
        public System.String First_Name { get; set; }
        public System.String EB_WB { get; set; }
    }

    #endregion

}
// </auto-generated>

